version: '3.1'
services:
    web:
        image: wordpress
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_PASSWORD: example
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
