version: '3'
services:
    web:
        image: nginx

        ports:
            - 80:80
        volumes:
            - ./:/var/www:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        environment:
            - NGINX_PORT=80
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    php:
        image: php:7-fpm
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www
